version: '3.9'
services:
  php-app-web:
    build: .
    ports:
      - 8080:80
    hostname: tubes-php-app
    env_file: .env
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php-app-db
  php-app-db:
    image: mysql:latest
    restart: always
    ports: 
      - 3308:3307
    expose:
      - 3307
    hostname: tubes-php-db
    env_file: .env
    volumes:
      - ./src/app/database/mysql:/docker-entrypoint-initdb.d/:ro
volumes:
  db:
    driver: local
networks:
  web-mysql:
    driver: bridge
